<?php
//Define interface class for router
use \Psr\Http\Message\ServerRequestInterface as Request;        //PSR7 ServerRequestInterface   >> Each router file must contains this
use \Psr\Http\Message\ResponseInterface as Response;            //PSR7 ResponseInterface        >> Each router file must contains this

//Define your modules class
use \modules\imagehoster\ImageHoster as ImageHoster;            //Your main modules class

//Define additional class for any purpose
use \classes\middleware\ValidateParam as ValidateParam;         //ValidateParam                 >> To validate the body form request
use \classes\middleware\ApiKey as ApiKey;                       //ApiKey Middleware             >> To authorize request by using ApiKey generated by reSlim

    
    // Get module information (include cache and for public user)
    $app->map(['GET','OPTIONS'],'/imagehoster/get/info/', function (Request $request, Response $response) {
        $ih = new ImageHoster($this->db);
        $body = $response->getBody();
        $response = $this->cache->withEtag($response, $this->etag2hour.'-'.trim($_SERVER['REQUEST_URI'],'/'));
        $body->write($ih->viewInfo());
        return classes\Cors::modify($response,$body,200,$request);
    })->add(new ApiKey);

    // Installation 
    $app->get('/imagehoster/install/{username}/{token}', function (Request $request, Response $response) {
        $ih = new ImageHoster($this->db);
        $ih->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $ih->username = $request->getAttribute('username');
        $ih->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($ih->install());
        return classes\Cors::modify($response,$body,200);
    });

    // Uninstall (This will clear all data) 
    $app->get('/imagehoster/uninstall/{username}/{token}', function (Request $request, Response $response) {
        $ih = new ImageHoster($this->db);
        $ih->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $ih->username = $request->getAttribute('username');
        $ih->token = $request->getAttribute('token');
        $body = $response->getBody();
        $body->write($ih->uninstall());
        return classes\Cors::modify($response,$body,200);
    });

    // POST api to delete
    $app->post('/imagehoster/data/delete', function (Request $request, Response $response) {
        $ih = new ImageHoster($this->db);
        $ih->lang = (empty($_GET['lang'])?$this->settings['language']:$_GET['lang']);
        $datapost = $request->getParsedBody();
        
        $ih->username = $datapost['Username'];
        $ih->token = $datapost['Token'];
        $ih->id = $datapost['ID'];

        $body = $response->getBody();
        $body->write($ih->delete());
        return classes\Cors::modify($response,$body,200);
    })->add(new ValidateParam('ID','1-20','alphanumeric'))
        ->add(new ValidateParam('Token','1-250','required'))
        ->add(new ValidateParam('Username','1-50','required'));